# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Compiles resume for www.yasirfayrooz.com

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          extra_fonts: |
            ./fonts/*.otf
          latexmk_use_lualatex: true
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: yasir-fayrooz-latest-resume.pdf
      
      - name: Publish PDF to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: '*.pdf'
          commit_message: Compiled yasirs latest resume